"""Stage 1 immutable business-schema baseline."""
from alembic import op
import sqlalchemy as sa

revision="20260801_initial"
down_revision=None
branch_labels=None
depends_on=None


def _indexes(table: str, columns: tuple[str, ...]) -> None:
    for column in columns: op.create_index(f"ix_{table}_{column}",table,[column])


def upgrade():
    op.create_table("users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("username",sa.String(64),nullable=False),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("display_name",sa.String(80),nullable=False),sa.Column("phone_masked",sa.String(32),nullable=False),sa.Column("role",sa.String(32),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False));op.create_index("ix_users_username","users",["username"],unique=True);_indexes("users",("role",))
    op.create_table("properties",sa.Column("id",sa.String(36),primary_key=True),sa.Column("community_name",sa.String(100),nullable=False),sa.Column("building_no",sa.String(12),nullable=False),sa.Column("unit_no",sa.String(12),nullable=False),sa.Column("room_no",sa.String(12),nullable=False),sa.Column("floor",sa.Integer(),nullable=False),sa.Column("property_type",sa.String(32),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("community_name","building_no","unit_no","room_no",name="uq_property_address"));_indexes("properties",("community_name","building_no"))
    op.create_table("user_property_bindings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("user_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("property_id",sa.String(36),sa.ForeignKey("properties.id"),nullable=False),sa.Column("binding_type",sa.String(32),nullable=False),sa.Column("is_primary",sa.Boolean(),nullable=False),sa.Column("verified_at",sa.DateTime(),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("user_id","property_id",name="uq_user_property_binding"));_indexes("user_property_bindings",("user_id","property_id"))
    op.create_table("work_orders",sa.Column("id",sa.String(36),primary_key=True),sa.Column("work_order_no",sa.String(32),nullable=False),sa.Column("requester_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("property_id",sa.String(36),sa.ForeignKey("properties.id"),nullable=False),sa.Column("original_description",sa.Text(),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("category",sa.String(32),nullable=False),sa.Column("subcategory",sa.String(32)),sa.Column("location_description",sa.String(200),nullable=False),sa.Column("equipment_name",sa.String(100)),sa.Column("fault_description",sa.Text(),nullable=False),sa.Column("impact_scope",sa.String(32),nullable=False),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("priority",sa.String(8),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("assignee_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("contact_phone_masked",sa.String(32),nullable=False),sa.Column("request_channel",sa.String(32),nullable=False),sa.Column("requires_manual_escalation",sa.Boolean(),nullable=False),sa.Column("manual_escalation_reason",sa.Text()),sa.Column("resolution",sa.Text()),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("idempotency_key",sa.String(100),unique=True),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("accepted_at",sa.DateTime()),sa.Column("assigned_at",sa.DateTime()),sa.Column("started_at",sa.DateTime()),sa.Column("completed_at",sa.DateTime()),sa.Column("closed_at",sa.DateTime()),sa.Column("updated_at",sa.DateTime(),nullable=False));op.create_index("ix_work_orders_work_order_no","work_orders",["work_order_no"],unique=True);_indexes("work_orders",("requester_id","property_id","category","risk_level","priority","status","assignee_id","created_at"))
    op.create_table("work_order_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("work_order_id",sa.String(36),sa.ForeignKey("work_orders.id"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("from_status",sa.String(16)),sa.Column("to_status",sa.String(16)),sa.Column("operator_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("note",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False));_indexes("work_order_events",("work_order_id",))
    op.create_table("work_order_ratings",sa.Column("id",sa.String(36),primary_key=True),sa.Column("work_order_id",sa.String(36),sa.ForeignKey("work_orders.id"),nullable=False,unique=True),sa.Column("resident_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("score",sa.Integer(),nullable=False),sa.Column("comment",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False))
    op.create_table("announcements",sa.Column("id",sa.String(36),primary_key=True),sa.Column("title",sa.String(160),nullable=False),sa.Column("announcement_type",sa.String(32),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("affected_scope",sa.String(160),nullable=False),sa.Column("start_time",sa.DateTime()),sa.Column("end_time",sa.DateTime()),sa.Column("contact_information",sa.String(160),nullable=False),sa.Column("publisher_unit",sa.String(100),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("reviewed_by",sa.String(36),sa.ForeignKey("users.id")),sa.Column("published_by",sa.String(36),sa.ForeignKey("users.id")),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("reviewed_at",sa.DateTime()),sa.Column("published_at",sa.DateTime()),sa.Column("updated_at",sa.DateTime(),nullable=False));_indexes("announcements",("status",))
    op.create_table("bills",sa.Column("id",sa.String(36),primary_key=True),sa.Column("bill_no",sa.String(32),nullable=False),sa.Column("property_id",sa.String(36),sa.ForeignKey("properties.id"),nullable=False),sa.Column("billing_period",sa.String(7),nullable=False),sa.Column("bill_type",sa.String(32),nullable=False),sa.Column("amount",sa.Numeric(12,2),nullable=False),sa.Column("paid_amount",sa.Numeric(12,2),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("due_date",sa.DateTime(),nullable=False),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));op.create_index("ix_bills_bill_no","bills",["bill_no"],unique=True);_indexes("bills",("property_id","billing_period"))
    op.create_table("payment_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("bill_id",sa.String(36),sa.ForeignKey("bills.id"),nullable=False),sa.Column("payment_no",sa.String(32),nullable=False,unique=True),sa.Column("amount",sa.Numeric(12,2),nullable=False),sa.Column("paid_at",sa.DateTime(),nullable=False),sa.Column("payment_channel",sa.String(32),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False));_indexes("payment_records",("bill_id",))
    op.create_table("bill_review_requests",sa.Column("id",sa.String(36),primary_key=True),sa.Column("request_no",sa.String(32),nullable=False,unique=True),sa.Column("bill_id",sa.String(36),sa.ForeignKey("bills.id"),nullable=False),sa.Column("resident_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("reason",sa.Text(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("handler_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("result",sa.Text()),sa.Column("idempotency_key",sa.String(100),unique=True),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("handled_at",sa.DateTime()));_indexes("bill_review_requests",("bill_id","resident_id"))
    op.create_table("inspection_tasks",sa.Column("id",sa.String(36),primary_key=True),sa.Column("task_no",sa.String(32),nullable=False,unique=True),sa.Column("area_type",sa.String(32),nullable=False),sa.Column("location_description",sa.String(200),nullable=False),sa.Column("scheduled_at",sa.DateTime(),nullable=False),sa.Column("assignee_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_by",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("completed_at",sa.DateTime()));_indexes("inspection_tasks",("assignee_id",))
    op.create_table("inspection_records",sa.Column("id",sa.String(36),primary_key=True),sa.Column("inspection_task_id",sa.String(36),sa.ForeignKey("inspection_tasks.id"),nullable=False),sa.Column("inspector_id",sa.String(36),sa.ForeignKey("users.id"),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("abnormal",sa.Boolean(),nullable=False),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("attachment_path",sa.String(255)),sa.Column("submitted_at",sa.DateTime(),nullable=False),sa.Column("idempotency_key",sa.String(100),unique=True));_indexes("inspection_records",("inspection_task_id",))
    op.create_table("rectification_orders",sa.Column("id",sa.String(36),primary_key=True),sa.Column("rectification_no",sa.String(32),nullable=False,unique=True),sa.Column("inspection_record_id",sa.String(36),sa.ForeignKey("inspection_records.id"),nullable=False,unique=True),sa.Column("description",sa.Text(),nullable=False),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("assignee_id",sa.String(36),sa.ForeignKey("users.id")),sa.Column("deadline",sa.DateTime(),nullable=False),sa.Column("resolution",sa.Text()),sa.Column("review_result",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("completed_at",sa.DateTime()),sa.Column("reviewed_at",sa.DateTime()))
    op.create_table("audit_logs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("actor_id",sa.String(36)),sa.Column("actor_role",sa.String(32)),sa.Column("action",sa.String(80),nullable=False),sa.Column("resource_type",sa.String(40),nullable=False),sa.Column("resource_id",sa.String(36)),sa.Column("request_method",sa.String(12)),sa.Column("request_path",sa.String(255)),sa.Column("request_id",sa.String(64),nullable=False),sa.Column("result",sa.String(16),nullable=False),sa.Column("failure_reason",sa.String(255)),sa.Column("metadata_json",sa.Text()),sa.Column("created_at",sa.DateTime(),nullable=False));_indexes("audit_logs",("actor_id","action","request_id"))


def downgrade():
    for table in ("audit_logs","rectification_orders","inspection_records","inspection_tasks","bill_review_requests","payment_records","bills","announcements","work_order_ratings","work_order_events","work_orders","user_property_bindings","properties","users"):op.drop_table(table)
