"""Dataset choices are explicit so re-runs never silently change the evidence base."""
from __future__ import annotations

from .types import DatasetSpec

NYC_TERMS = "https://opendata.cityofnewyork.us/overview/"

NYC_HPD_COMPLAINTS = DatasetSpec(
    dataset_id="ygpa-z7cr", slug="nyc_hpd_complaints", name="Housing Maintenance Code Complaints and Problems",
    domain="data.cityofnewyork.us", country="US", city="New York City",
    publisher="NYC Department of Housing Preservation and Development (HPD)",
    source_url="https://data.cityofnewyork.us/Housing-Development/Housing-Maintenance-Code-Complaints-and-Problems/ygpa-z7cr",
    api_url="https://data.cityofnewyork.us/resource/ygpa-z7cr.json",
    download_url="https://data.cityofnewyork.us/api/views/ygpa-z7cr/rows.csv?accessType=DOWNLOAD",
    license="NYC Open Data terms: public datasets available without registration, license requirement, or usage restrictions; NYC.gov terms also apply",
    license_url=NYC_TERMS, record_kind="work_order", source_id_field="problem_id",
    selected_fields=("received_date", "problem_id", "complaint_id", "building_id", "borough", "post_code", "community_board", "unit_type", "space_type", "type", "major_category", "minor_category", "problem_code", "complaint_status", "complaint_status_date", "problem_status", "problem_status_date", "status_description", "problem_duplicate_flag", "complaint_anonymous_flag"),
    order="received_date DESC, problem_id DESC", category_field="major_category", source_row_count=16_227_351,
    strata=("HEATING", "HEAT/HOT WATER", "PLUMBING", "GENERAL", "PAINT/PLASTER", "UNSANITARY CONDITION", "NONCONST", "ELECTRIC", "DOOR/WINDOW", "WATER LEAK", "APPLIANCE", "FLOORING/STAIRS", "SAFETY", "CONSTRUCTION", "OUTSIDE BUILDING", "ELEVATOR"),
    extra_notes="Only minimised, non-address fields are requested. A complaint problem is not represented as a real resident work order.",
)

NYC_HPD_VIOLATIONS = DatasetSpec(
    dataset_id="wvxf-dwi5", slug="nyc_hpd_violations", name="Housing Maintenance Code Violations",
    domain="data.cityofnewyork.us", country="US", city="New York City",
    publisher="NYC Department of Housing Preservation and Development (HPD)",
    source_url="https://data.cityofnewyork.us/Housing-Development/Housing-Maintenance-Code-Violations/wvxf-dwi5",
    api_url="https://data.cityofnewyork.us/resource/wvxf-dwi5.json",
    download_url="https://data.cityofnewyork.us/api/views/wvxf-dwi5/rows.csv?accessType=DOWNLOAD",
    license="NYC Open Data terms: public datasets available without registration, license requirement, or usage restrictions; NYC.gov terms also apply",
    license_url=NYC_TERMS, record_kind="inspection_rectification", source_id_field="violationid",
    selected_fields=("violationid", "buildingid", "boro", "zip", "class", "inspectiondate", "approveddate", "originalcertifybydate", "originalcorrectbydate", "novdescription", "novissueddate", "currentstatus", "currentstatusdate", "violationstatus", "rentimpairing"),
    order="inspectiondate DESC, violationid DESC", category_field="class", source_row_count=11_150_614, strata=("A", "B", "C", "I"),
    extra_notes="HPD states these violations are issued by Housing Inspectors after physical inspection except generally administrative class I violations. They are historical public regulatory records, not current property condition.",
)

SELECTED_DATASETS = (NYC_HPD_COMPLAINTS, NYC_HPD_VIOLATIONS)


def candidate_rows() -> list[dict[str, str]]:
    """Verified research snapshot. Scores use the documented 30/20/15/15/10/10 rubric."""
    verified = "2026-08-07T00:00:00+08:00"
    rows = [
        {"dataset_id":"ez4a-iug7","dataset_name":"Seattle Code Complaints and Violations","country":"US","city":"Seattle","publisher":"Seattle Department of Construction & Inspections","official_source":"yes","source_url":"https://data.seattle.gov/Built-Environment/Code-Complaints-and-Violations/ez4a-iug7","api_url":"https://data.seattle.gov/resource/ez4a-iug7.json","download_url":"https://data.seattle.gov/api/views/ez4a-iug7/rows.csv?accessType=DOWNLOAD","last_updated":"2026-07-29","row_count":"244232","column_count":"17","has_free_text":"yes","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"yes","has_resolution":"yes","contains_personal_data":"possible in description/address","license":"Public Domain","license_verified":"yes","download_access":"official API metadata verified; direct fetch returned 403 in this execution environment","relevance_work_order":"95","relevance_inspection":"75","relevance_rectification":"70","relevance_rag":"70","data_quality_score":"88","business_match_score":"91","license_score":"100","accessibility_score":"55","final_score":"84.3","selected":"no","selection_reason":"","rejection_reason":"Runtime direct API access was denied (HTTP 403); not substituted with an unofficial mirror.","verified_at":verified},
        {"dataset_id":"wb4c-6hwj","dataset_name":"San Francisco Fire Inspections","country":"US","city":"San Francisco","publisher":"San Francisco Fire Department / DataSF","official_source":"yes","source_url":"https://data.sfgov.org/Housing-and-Buildings/Fire-Inspections/wb4c-6hwj","api_url":"https://data.sfgov.org/resource/wb4c-6hwj.json","download_url":"https://data.sfgov.org/api/views/wb4c-6hwj/rows.csv?accessType=DOWNLOAD","last_updated":"2026-07-20","row_count":"not returned by portal","column_count":"37","has_free_text":"limited","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"no","has_resolution":"yes","contains_personal_data":"address","license":"Open Data Commons Public Domain Dedication and License (PDDL)","license_verified":"yes","download_access":"official API metadata verified; direct fetch returned 403 in this execution environment","relevance_work_order":"55","relevance_inspection":"97","relevance_rectification":"65","relevance_rag":"55","data_quality_score":"86","business_match_score":"84","license_score":"100","accessibility_score":"55","final_score":"81.4","selected":"no","selection_reason":"","rejection_reason":"Runtime direct API access was denied (HTTP 403); no bypass attempted.","verified_at":verified},
        {"dataset_id":"4zuq-2cbe","dataset_name":"San Francisco Fire Violations","country":"US","city":"San Francisco","publisher":"San Francisco Fire Department / DataSF","official_source":"yes","source_url":"https://data.sfgov.org/Housing-and-Buildings/Fire-Violations/4zuq-2cbe","api_url":"https://data.sfgov.org/resource/4zuq-2cbe.json","download_url":"https://data.sfgov.org/api/views/4zuq-2cbe/rows.csv?accessType=DOWNLOAD","last_updated":"2026-07-19","row_count":"not returned by portal","column_count":"24","has_free_text":"yes","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"yes","has_resolution":"yes","contains_personal_data":"address","license":"Open Data Commons Public Domain Dedication and License (PDDL)","license_verified":"yes","download_access":"official API metadata verified; direct fetch returned 403 in this execution environment","relevance_work_order":"65","relevance_inspection":"78","relevance_rectification":"98","relevance_rag":"70","data_quality_score":"87","business_match_score":"90","license_score":"100","accessibility_score":"55","final_score":"83.0","selected":"no","selection_reason":"","rejection_reason":"Runtime direct API access was denied (HTTP 403); no bypass attempted.","verified_at":verified},
        {"dataset_id":"ygpa-z7cr","dataset_name":"Housing Maintenance Code Complaints and Problems","country":"US","city":"New York City","publisher":"NYC Department of Housing Preservation and Development (HPD)","official_source":"yes","source_url":NYC_HPD_COMPLAINTS.source_url,"api_url":NYC_HPD_COMPLAINTS.api_url,"download_url":NYC_HPD_COMPLAINTS.download_url,"last_updated":"2026-08-06","row_count":"16227351","column_count":"34","has_free_text":"limited","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"yes","has_resolution":"yes","contains_personal_data":"location and free status text; minimised query and sanitization applied","license":"NYC Open Data terms","license_verified":"yes","download_access":"official API verified","relevance_work_order":"96","relevance_inspection":"70","relevance_rectification":"75","relevance_rag":"75","data_quality_score":"91","business_match_score":"93","license_score":"92","accessibility_score":"95","final_score":"92.0","selected":"yes","selection_reason":"Official, accessible HPD residential-maintenance complaint data with categories, status and date fields; selected as public-real historic work-order cases.","rejection_reason":"","verified_at":verified},
        {"dataset_id":"wvxf-dwi5","dataset_name":"Housing Maintenance Code Violations","country":"US","city":"New York City","publisher":"NYC Department of Housing Preservation and Development (HPD)","official_source":"yes","source_url":NYC_HPD_VIOLATIONS.source_url,"api_url":NYC_HPD_VIOLATIONS.api_url,"download_url":NYC_HPD_VIOLATIONS.download_url,"last_updated":"2026-08-06","row_count":"11150614","column_count":"35","has_free_text":"yes","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"yes","has_resolution":"yes","contains_personal_data":"address/unit may occur in description; raw is access-minimised and normalized text is sanitized","license":"NYC Open Data terms","license_verified":"yes","download_access":"official API verified","relevance_work_order":"76","relevance_inspection":"96","relevance_rectification":"98","relevance_rag":"76","data_quality_score":"90","business_match_score":"95","license_score":"92","accessibility_score":"95","final_score":"93.1","selected":"yes","selection_reason":"Official HPD regulatory data; description, inspection date, class and current status provide a non-fabricated inspection/rectification history.","rejection_reason":"","verified_at":verified},
        {"dataset_id":"22u3-xenr","dataset_name":"Chicago Building Violations","country":"US","city":"Chicago","publisher":"City of Chicago Department of Buildings","official_source":"yes","source_url":"https://data.cityofchicago.org/Buildings/Building-Violations/22u3-xenr","api_url":"https://data.cityofchicago.org/resource/22u3-xenr.json","download_url":"https://data.cityofchicago.org/api/views/22u3-xenr/rows.csv?accessType=DOWNLOAD","last_updated":"2026-07-28","row_count":"2021952","column_count":"26","has_free_text":"yes","has_category":"yes","has_status":"yes","has_created_time":"yes","has_completed_time":"yes","has_location":"yes","has_inspection":"yes","has_violation":"yes","has_resolution":"yes","contains_personal_data":"address/owner field","license":"Unspecified on dataset page","license_verified":"yes","download_access":"official API verified","relevance_work_order":"75","relevance_inspection":"92","relevance_rectification":"92","relevance_rag":"75","data_quality_score":"88","business_match_score":"88","license_score":"20","accessibility_score":"94","final_score":"76.0","selected":"no","selection_reason":"","rejection_reason":"Dataset page reports an unspecified license, so it is not used as core public-real data.","verified_at":verified},
    ]
    return rows
